const controls = [
  {
    id: 1,
    name: 'Daryl Sweeney',
    reportsTo: null,
    phone: '(555) 924-9726',
    extension: 8253,
    hireDate: new Date(2012, 2, 7),
    fullTime: true,
    position: 'CEO',
    timeInPosition: 2,
    subcontrols: [
      {
        id: 2,
        name: 'Guy Wooten',
        reportsTo: 1,
        phone: '(438) 738-4935',
        extension: 1155,
        hireDate: new Date(2010, 3, 3),
        fullTime: true,
        position: 'Chief Technical Officer',
        timeInPosition: 1,
      },
      {
        id: 3,
        name: 'Priscilla Frank',
        reportsTo: 1,
        phone: '(278) 927-2684',
        extension: 4183,
        hireDate: new Date(2014, 11, 30),
        fullTime: true,
        position: 'Chief Product Officer',
        timeInPosition: 2,
        subcontrols: [
          {
            id: 4,
            name: 'Ursula Holmes',
            reportsTo: 3,
            phone: '(302) 760-2034',
            extension: 2226,
            hireDate: new Date(2011, 6, 6),
            fullTime: true,
            position: 'EVP, Product Strategy',
            timeInPosition: 4,
          },
          {
            id: 24,
            name: 'Melvin Carrillo',
            reportsTo: 3,
            phone: '(348) 933-5167',
            extension: 2482,
            hireDate: new Date(2014, 7, 21),
            fullTime: true,
            position: 'Director, Developer Relations',
            timeInPosition: 6,
            controls: [
              {
                id: 29,
                name: 'Martha Chavez',
                reportsTo: 24,
                phone: '(860) 754-3464',
                extension: 4531,
                hireDate: new Date(2013, 3, 12),
                fullTime: true,
                position: 'Developer Advocate',
                timeInPosition: 0,
              },
              {
                id: 30,
                name: 'Oren Fox',
                reportsTo: 24,
                phone: '(572) 414-3299',
                extension: 4849,
                hireDate: new Date(2013, 5, 14),
                fullTime: false,
                position: 'Developer Advocate',
                timeInPosition: 0,
              },
              {
                id: 41,
                name: 'Amos Barr',
                reportsTo: 24,
                phone: '(470) 381-3718',
                extension: 7643,
                hireDate: new Date(2010, 3, 9),
                fullTime: true,
                position: 'Developer Advocate',
                timeInPosition: 2,
              },
            ],
          },
        ],
      },
    ],
  },
];

export default controls;
